### PR TITLE
Improved "ignored" option: ignore subdirectory

### PR DESCRIPTION
**Pull request by razonyang**

### CODE REVIEW

**Comment by annismckenzie** [comment]
Just ran into this. Please, please, please consider accepting this patch. :)

**Comment by dashaus** [comment]
I think that this solution is the same but with less line:
```go
for _, e := range strings.Split(settings["ignored"], ",") {
		if strings.Contains(path, strings.TrimSpace(e)) {
			return true
		}
	}
```

**Comment by dashaus** [comment]
Anyway,I think that this should be merged as soon as possible 👍

**Comment by razonyang** [comment]
@dashaus your code seems better than this, I didn't know before.
Could you create a new PR? And then I will close this :) :+1:

**Comment by dashaus** [comment]
If you want, you can take my code and put it in your PR.  ;)

**Comment by razonyang** [comment]
@dashaus I reviewed your code, but it doesn't work correctly. For example:
ignored path: `app`, and the current path is `apps`, expected `false` , but got `true`.

**Comment by dashaus** [comment]
Ops... Yes, you right!

**Comment by gmccue** [comment]
Just so I understand the problem this solves... this is because currently all `subdirectories` are ignored? So if `/app` is ignored, but you still want `/app/users` to not be ignored you would be able to do so? Or am I missing something ?

**Comment by razonyang** [comment]
@gmccue In my application structure:

- models
- frontend/controllers
- frontend/node_modules
- frontend/server.go

I want to watch `models` directory and ignore the `frontend/node_modules` directory, but `fresh` does not allow to do this, it would ignore all `subudirectories` of `frontend`.

**Pull request closed without merging**
