### PR TITLE
Add a build_args setting

### PR DESCRIPTION
**Pull request by lpetre**
This controls what is passed to `go build`.  In our use case our main.go isn't in the root directory, but we want to watch the entire root for file changes. So I pass RUNNER_BUILD_ARGS=./cmd/app to fresh

### CODE REVIEW

**Comment by lpetre** [comment]
@gmccue yep, no problem.

**Comment by gmccue** [comment]
Sorry for the delay here.. I'll try to get this merged very soon.

**Comment by curio77** [comment]
Interested in this too! Any chance we get a merge anytime soon?

**Comment by mattkanwisher** [comment]
This didn't work for me, so I tweaked it slightly and added to my repo.
I'm collecting the best patches and applying to a new repo cause this one seems dead https://github.com/loomnetwork/fresh

**Comment by gravityblast** [comment]
hey @mattkanwisher, thank you! yes that's the best thing to do, this repo is unmaintained!

**Pull request closed without merging**
